server:
  servlet:
    context-path: /admin
spring:
  application:
    name: harvey-admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: @activeProfile@, core

# jwt
jwt:
  # 令牌前缀
  token-start-with: Bearer
  base64-secret: ZWQ0ZGI5NjQ0MGR3NDBjYjgyMzFjZjdmYjcyN2E3ZmYyM2E4Yjk4NWRhNDUwYzBjODQwNzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1cjg1ZGQ1OWNmNzhmMGVhNTc1Mzk1ZDZiMWNkNzQ0Y2VlNjJkNzI2NTcyZjUxNDMydw==
  # token 过期时间，单位：分钟
  expire-time: 60

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.harvey.system.controller
