server:
  servlet:
    context-path: /admin
spring:
  application:
    name: harvey-admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null
  profiles:
    active: @activeProfile@, core

management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
      base-path: /actuator

# sa-token
sa-token:
  # token 名称（同时也是请求头 key）
  token-name: Authorization
  # token 前缀，前端携带的 token 为：Bearer <token>
  token-prefix: Bearer
  # token 有效期，单位：秒（默认 30 天）
  timeout: 3600
  # token 临时有效期（指定时间内无操作就视为 token 过期），单位：秒，-1 表示不设
  active-timeout: -1
  # 是否允许同一账号并发登录（为 true 时允许一起登录，为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token（为 true 时所有登录共用一个 token，为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否在初始化配置时打印版本字符画
  is-print: false
  # 关闭 cookie 读取，前后端分离
  is-read-cookie: false

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.harvey.system.controller
