server:
  servlet:
    context-path: /admin
spring:
  application:
    name: harvey-admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master: # 主库
          driver-class-name: com.mysql.cj.jdbc.Driver
          #      url: jdbc:mysql://127.0.0.1:3306/harvey?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          url: jdbc:mysql://127.0.0.1:3306/harvey?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
        slave_1: # 从库1
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/harvey?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始创建时建立的连接数
      min-idle: 5 #最小空闲连接数
      max-active: 20 #最大的连接池数量
      max-wait: 60000 #获取连接的最大等待毫秒数
      time-between-eviction-runs-millis: 60000 #两个连接空闲检查之间的时间间隔
      min-evictable-idle-time-millis: 30000 #连接在池中最小生存时间后才允许被驱逐
      validation-query: select 'x' #检查连接是否可用的 SQL 查询
      test-while-idle: true #申请连接前检测连接是否有效
      test-on-borrow: false #申请连接时进行连接有效性检验
      test-on-return: false #归还连接时进行连接有效性检验
      pool-prepared-statements: false #是否开启 PreparedStatement 的缓存
#      filters: stat,wall,slf4j #配置扩展插件，常用的有 stat（监控统计）、wall（SQL防火墙）、log4j（日志）等
      max-pool-prepared-statement-per-connection-size: -1 #每个连接上PSCache最大语句数
      use-global-data-source-stat: true #是否开启合并Stat
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000 #连接属性，用于合并 SQL 和设置慢 SQL 的阈值
      web-stat-filter:
        enabled: true #是否启用该过滤器
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true #是否启用监控页面
        url-pattern: /druid/*
        reset-enable: false #是否允许重置监控数据
        login-username: druid #登录监控页面所需的用户名
        login-password: druid #登录监控页面所需的密码
        allow: 127.0.0.1 #允许访问监控页面的 IP 地址或地址段列表
        deny: #明确拒绝访问监控页面的 IP 地址或地址段列表。如果留空，则默认拒绝所有未在 allow 中列出的 IP 地址。

  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379
      timeout: 5000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms


# MyBatisPlus??
mybatis-plus:
  type-aliases-package: com.harvey.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-underline: true
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 0 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值

#jwt
jwt:
  # 令牌前缀
  token-start-with: Bearer
  base64-secret: ZWQ0ZGI5NjQ0MGR3NDBjYjgyMzFjZjdmYjcyN2E3ZmYyM2E4Yjk4NWRhNDUwYzBjODQwNzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1cjg1ZGQ1OWNmNzhmMGVhNTc1Mzk1ZDZiMWNkNzQ0Y2VlNjJkNzI2NTcyZjUxNDMydw==
  # token 过期时间，单位：分钟
  expire-time: 60

executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 100
  keepalive-seconds: 10
  thread-name-prefix: harvey-

xxl:
  job:
    # 定时任务开关
    enabled: false
    admin:
      # 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
    # 调度中心通讯TOKEN [选填]：非空时启用；
    accessToken: default_token
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: xxl-job-executor-harvey
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9999
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: /data/applogs/xxl-job/jobhandler
      # 调度中心日志表数据保存天数 [必填]：过期日志自动清理；限制大于等于7时生效，否则, 如-1，关闭自动清理功能；
      logretentiondays: 30

# 对象存储配置
storage:
  # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
  active: local
  # 本地对象存储配置信息
  local:
    storagePath: G:/storage
    # fetch方法对应的地址
    address: /storage/fetch/
  # 阿里云对象存储配置信息
  aliyun:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI3RId6XqBVVgn
    accessKeySecret: gbqTsES0eGJTIPefYaQPP9pPammQyy
    bucketName: hnyystatic
  # 腾讯对象存储配置信息，请参考 https://cloud.tencent.com/document/product/436/6249
  tencent:
    secretId: AKIDOccMr856uoU1Tsa2MQL5aqseBUWRrb5i
    secretKey: XqtgEhIdrupTs4ygaWlkUUXv3w3FiwuD
    region: ap-shanghai
    bucketName: vytech-1300096589
  # 七牛云对象存储配置信息
  qiniu:
    endpoint: http://pd5cb6ulu.bkt.clouddn.com
    accessKey: 111111
    secretKey: xxxxxx
    bucketName: mall

log:
  path: /opt/springboot/web

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.harvey.system.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn