<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.harvey</groupId>
        <artifactId>harvey-boot</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>harvey-screen</artifactId>
    <name>${project.artifactId}</name>
    <packaging>pom</packaging>
    <description>harvey-screen 信发模块</description>

    <modules>
        <module>harvey-screen-api</module>
        <module>harvey-screen-tcp</module>
        <module>harvey-screen-service</module>
        <module>harvey-screen-demo</module>
    </modules>
</project>