# MyBatisPlus配置
mybatis-plus:
  type-aliases-package: com.harvey.**.entity
  mapper-locations: classpath*:mapper/*Mapper.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-underline: true
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 0 # 逻辑已删除值
      logic-not-delete-value: 1 # 逻辑未删除值

