xxl:
  job:
    access-token: default_token
    # 不同服务需要设置为不同的端口
    executor-port: ${EXECUTOR_PORT:9999}
    admin-addresses: http://${XXL_JOB_HOST:localhost}:${XXL_JOB_PORT:8100}/xxl-job-admin
    app-name: ${spring.application.name}-executor
    log-path: /opt/logs/xxl-job/handler
    log-retention-days: 30