spring:
  application:
    name: harvey-cloud-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/harvey
      username: root
      password: 123456

# MyBatisPlus??
mybatis-plus:
  type-aliases-package: com.harvey.**.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-underline: true
      logic-delete-field: deleted
      logic-delete-value: 0
      logic-not-delete-value: 1

# PageHelper????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

log:
  path: /opt/springboot/web